// File: TiffSegments.hxx
// This file is part of the project: Rewrap-jpeg-as-tiff -- Rewraps a jpeg file into a TIFF container, without loss of information (no re-encoding).
// Copyright(c) 2018 Vidar Bosnes
// This software is licenced under the GNU GENERAL PUBLIC LICENSE Version 3

#ifndef TIFFTAG_MACRO
#define TIFFTAG_MACRO(name, dir, type, value) // Silence Intellisense errors.
#endif

TIFFTAG_MACRO(  NewSubfileType,              Main,       Long,      254    )
TIFFTAG_MACRO(  ImageWidth,                  Main,       LongShort, 256    )
TIFFTAG_MACRO(  ImageLength,                 Main,       LongShort, 257    )
TIFFTAG_MACRO(  BitsPerSample,               Main,       Short,     258    )
TIFFTAG_MACRO(  Compression,                 Main,       Short,     259    )
TIFFTAG_MACRO(  PhotometricInterpretation,   Main,       Short,     262    )
TIFFTAG_MACRO(  ImageDescription,            Main,       Ascii,     270    )
TIFFTAG_MACRO(  Make,                        Main,       Ascii,     271    )
TIFFTAG_MACRO(  Model,                       Main,       Ascii,     272    )
TIFFTAG_MACRO(  StripOffsets,                Main,       LongShort, 273    )
TIFFTAG_MACRO(  Orientation,                 Main,       Short,     274    )
TIFFTAG_MACRO(  SamplesPerPixel,             Main,       Short,     277    )
TIFFTAG_MACRO(  RowsPerStrip,                Main,       LongShort, 278    )
TIFFTAG_MACRO(  StripByteCounts,             Main,       LongShort, 279    )
TIFFTAG_MACRO(  XResolution,                 Main,       Rational,  282    )
TIFFTAG_MACRO(  YResolution,                 Main,       Rational,  283    )
TIFFTAG_MACRO(  PlanarConfig,                Main,       Short,     284    )
TIFFTAG_MACRO(  ResolutionUnit,              Main,       Short,     296    )
TIFFTAG_MACRO(  Software,                    Main,       Ascii,     305    )
TIFFTAG_MACRO(  DateTime,                    Main,       Ascii,     306    )
TIFFTAG_MACRO(  Artist,                      Main,       Ascii,     315    )
TIFFTAG_MACRO(  HostComputer,                Main,       Ascii,     316    )
TIFFTAG_MACRO(  Predictor,                   Main,       Short,     317    )
TIFFTAG_MACRO(  TileWidth,                   Main,       LongShort, 322    )
TIFFTAG_MACRO(  TileLength,                  Main,       LongShort, 323    )
TIFFTAG_MACRO(  TileOffsets,                 Main,       Long,      324    )
TIFFTAG_MACRO(  TileByteCounts,              Main,       LongShort, 325    )
TIFFTAG_MACRO(  SubIFDs,                     Main,       IFD,       330    )
TIFFTAG_MACRO(  JPEGTables,                  Main,       Xbytes,    347    )
TIFFTAG_MACRO(  JPEGInterchangeFormat,       Main,       Long,      513    )
TIFFTAG_MACRO(  JPEGInterchangeFormatLength, Main,       Long,      514    )
TIFFTAG_MACRO(  YCbCrCoefficients,           Main,       Rational,  529    )
TIFFTAG_MACRO(  YCbCrSubSampling,            Main,       Short,     530    )
TIFFTAG_MACRO(  YCbCrPositioning,            Main,       Short,     531    )
TIFFTAG_MACRO(  ReferenceBlackWhite,         Main,       Rational,  532    )
TIFFTAG_MACRO(  XMP,                         Main,       Byte,      700    )
TIFFTAG_MACRO(  Copyright,                   Main,       Ascii,     33432  )
TIFFTAG_MACRO(  Exposure,                    Exif,       Rational,  33434  )
TIFFTAG_MACRO(  FNumber,                     Exif,       Rational,  33437  )
TIFFTAG_MACRO(  IPTCNAA,                     Main,       XbyteByte, 33723  )
TIFFTAG_MACRO(  PhotoshopImageResources,     Main,       Byte,      34377  )
TIFFTAG_MACRO(  ExifIFD,                     Main,       Long,      34665  )
TIFFTAG_MACRO(  IccProfile,                  Main,       Xbyte,     34675  )
TIFFTAG_MACRO(  GPSIFD,                      Main,       Long,      34853  )
TIFFTAG_MACRO(  MakerNote,                   Exif,       Xbyte,     37500  )
TIFFTAG_MACRO(  ExifPixelXDimension,         Exif,       LongShort, 40962  )
TIFFTAG_MACRO(  ExifPixelYDimension,         Exif,       LongShort, 40963  )
TIFFTAG_MACRO(  InteroperabilityIFD,         Main,       Long,      40965  )
TIFFTAG_MACRO(  LensModel,                   Exif,       Ascii,     42036  )
TIFFTAG_MACRO(  CR2_50648,                   Image,      Long,      50648  )
TIFFTAG_MACRO(  CR2_50656,                   Image,      Long,      50656  )
TIFFTAG_MACRO(  DNGVersion,                  Main,       Byte,      50706  )
TIFFTAG_MACRO(  DNGBackwardVersion,          Main,       Byte,      50707  )
TIFFTAG_MACRO(  UniqueCameraModel,           Main,       Ascii,     50708  )
TIFFTAG_MACRO(  ColorMatrix1,                Main,       SRational, 50721  )
TIFFTAG_MACRO(  AnalogBalance,               Main,       Rational,  50727  )
TIFFTAG_MACRO(  AsShotWhiteXY,               Main,       Rational,  50729  )
TIFFTAG_MACRO(  BaselineExposure,            Main,       SRational, 50730  )
TIFFTAG_MACRO(  BaselineNoise,               Main,       Rational,  50731  )
TIFFTAG_MACRO(  BaselineSharpness,           Main,       Rational,  50732  )
TIFFTAG_MACRO(  LinearResponseLimit,         Main,       Rational,  50734  )
TIFFTAG_MACRO(  ShadowScale,                 Exif,       Rational,  50739  )
TIFFTAG_MACRO(  DNGPrivateData,              Main,       Byte,      50740  )
TIFFTAG_MACRO(  CR2_50752,                   Main,       Short,     50752  )
TIFFTAG_MACRO(  CalibrationIlluminant1,      Main,       Short,     50778  )
TIFFTAG_MACRO(  RawDataUniqueID,             Main,       Byte,      50781  )
TIFFTAG_MACRO(  ColorimetricReference,       Main,       Short,     50879  )
TIFFTAG_MACRO(  CR2_50885,                   Image,      Long,      50885  )
TIFFTAG_MACRO(  ProfileName,                 Main,       AsciiByte, 50936  )
TIFFTAG_MACRO(  ProfileEmbedPolicy,          Main,       Long,      50941  )
TIFFTAG_MACRO(  PreviewApplicationName,      PreviewIFD, AsciiByte, 50966  )
TIFFTAG_MACRO(  PreviewApplicationVersion,   PreviewIFD, AsciiByte, 50967  )
TIFFTAG_MACRO(  PreviewSettingsDigest,       PreviewIFD, Byte,      50969  )
TIFFTAG_MACRO(  PreviewColorSpace,           PreviewIFD, Long,      50970  )
TIFFTAG_MACRO(  PreviewDateTime,             PreviewIFD, Ascii,     50971  )
TIFFTAG_MACRO(  NewRawImageDigest,           Main,       Byted,     51111  )

